### ISSUE TITLE
Remover view e dados relacionados a vacinas de animais

### ISSUE THREAD

**Issue by JoseCage** [VaccineCard/front#20]
@acidiney como parte de melhorias na app, deve ser removido a view e qualquer informação sobre animais. Uma vez que as vacinas são apenas para pessoas.

**Comment by JoseCage** [comment]
@acidiney posso fechar a issue, certo?

**Comment by acidiney** [comment]
Feita

**Comment by JoseCage** [comment]
Boa. 🚀
